apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-spring-app.fullname" . }}
  labels:
    {{- include "test-spring-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "test-spring-app.selectorLabels" . | nindent 4 }}
